Added Nerdicons Plugin
lite-xl/lite-xl-plugins pull request #166
Opened 2022-12-08 17:03 UTC by techie-guy

# Nerdicons Plugin

### **This is an extension/modification of the [nonicons plugins](https://github.com/lite-xl/lite-xl-plugins/blob/master/plugins/nonicons.lua)**

## How to use:
1. Download a nerd font that you like from [nerdfonts.com.](https://nerdfonts.com)
2. Unzip the zip file that you downloaded.
3. Choose a font file from the unzipped directory and install it.
4. Copy the font file to ```.config/lite-xl/fonts``` or lite-xl data dir.
5. Open .config/lite-xl/init.lua, add ```config.plugins.nerdicons.nerd_font = renderer.font.load("Path to font file", size_of_icons * SCALE)```
5. Restart lite-xl, the icons should appear.

2022-12-09 20:38 UTC, Guldoman requested changes
I'll review more in depth later.

2022-12-09 20:38 UTC, Guldoman commented on plugins/nerdicons.lua
> +-- 4. Copy the font file to the lite-xl-dir/data/fonts and rename it to "icon-nerd-font.ttf".
Don't use the data dir for user-installed things. Use the user dir (.config/lite-xl).

2022-12-09 20:38 UTC, Guldoman commented on plugins/nerdicons.lua
> +local icon_font = renderer.font.load(DATADIR .. "/fonts/icon-nerd-font.ttf", 18.5 * SCALE)
```suggestion
local icon_font = renderer.font.load(USERDIR .. "/fonts/icon-nerd-font.ttf", 18.5 * SCALE)
```

2022-12-19 03:10 UTC, jgmdev commented
Whoa! Nice icons collection, seems to have all I need  for some plugins.

2023-01-20 01:02 UTC, adamharrison commented
Hey @techie-guy; I'm doing a big push to merge PRs and stuff; can you update this one to use the new manifest system instead? (Sorry). I'll review it as soon as that's done.

2023-01-20 05:50 UTC, closed without merging