Graphical file picker using Zenity
lite-xl/lite-xl-plugins pull request #312
Opened 2023-10-06 20:01 UTC by kmafeni04

With help from @Guldoman, made a plugin that allows for a graphical file picker using the zenity program on linux

2023-10-06 20:35 UTC, Guldoman requested changes
The trailing comma in the manifest is an issue, as it'll break `lpm`.

There is a bunch of repeated code that could be moved into a function, but it's alright for now.

I'm not sold on the plugin ID/filename/command prefixes being just `zenity` tho.

2023-10-06 20:35 UTC, Guldoman commented on manifest.json
> +        {
Would you mind aligning this?

2023-10-06 20:35 UTC, Guldoman commented on plugins/zenity.lua
> +			core.log("Saved " .. '"' .. dv.doc.filename  .. '"')
I guess you could do
```suggestion
			command.perform("doc:save")
```

2023-10-06 20:35 UTC, Guldoman commented on plugins/zenity.lua
> +			core.log("Saved as " .. '"' .. dv.doc.filename  .. '"')
```suggestion
			core.log('Saved as "%s"', dv.doc.filename)
```

2023-10-06 20:35 UTC, Guldoman commented on manifest.json
> +    },
```suggestion
    }
```
Trailing `,` breaks JSON.

2023-10-06 22:11 UTC, kmafeni04 commented
> I'm not sold on the plugin ID/filename/command prefixes being just `zenity` tho.

What could be a more suitable name, `gui_save`?

Also will make changes in the morning

2023-10-07 14:24 UTC, Guldoman commented
> What could be a more suitable name, `gui_filepicker`?

Yeah, that sounds a bit more descriptive.
I wonder if we should note that `zenity` is only available on linux (and kinda on macOS too).

2023-10-08 12:27 UTC, kmafeni04 commented
> Yeah, that sounds a bit more descriptive. I wonder if we should note that `zenity` is only available on linux (and kinda on macOS too).

That should be right

2023-10-09 14:12 UTC, merged