Clojure file extension fix patch
lite-xl/lite-xl-plugins pull request #421
Opened 2024-04-12 14:55 UTC by RohanVashisht1234

2024-04-12 19:09 UTC, RohanVashisht1234 commented
Ok, I have updated clojure file extensions to be correct

2024-04-13 08:33 UTC, Guldoman requested changes
This is adding completely irrelevant changes, please revert those.

2024-04-13 09:02 UTC, RohanVashisht1234 commented
That is due to language_bazel

2024-04-13 09:43 UTC, RohanVashisht1234 commented
ok, fixed it

2024-04-14 14:34 UTC, RohanVashisht1234 commented
I think the error has been fixed, but how will I know or test it?

2024-04-15 16:36 UTC, Guldoman requested changes
This still contains unrelated changes.

2024-04-16 02:51 UTC, RohanVashisht1234 commented
Ok, I think the unnecessary changes have been fixed

2024-04-16 17:43 UTC, Guldoman commented on manifest.json
> +      "version": "0.1.12"
```suggestion
      "version": "0.1.13"
```

2024-04-16 17:43 UTC, merged